; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "environment.iss"

#define MyAppName "ezr² Shell"
#define MyAppVersion "0.8.1"
#define MyAppPublisher "Urav Advanced Learning Systems Pvt Ltd"
#define MyAppURL "https://uralstech.github.io/ezrSquared/"
#define MyAppExeName "ezrSquared.exe"
#define MyAppAssocName "ezr² Script"
#define MyAppAssocExt ".ezr2"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B84F04C4-4945-4687-8455-7E179F3A05A0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=D:\Code\csharp\ezrSquared\LICENSE.txt
InfoAfterFile=D:\Code\csharp\ezrSquared\Changelog.txt
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\Code\csharp\ezrSquared\Binaries\Shell\Release\Installers
OutputBaseFilename=ezrSquared Shell Setup (Win64)
SetupIconFile=D:\Code\csharp\ezrSquared\graphics\Icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[LangOptions]
DialogFontSize=10

[CustomMessages]
WebDocumentation=%1 Online Documentation
LocalDocumentation=%1 Offline Documentation

[Types]
Name: "full"; Description: "Full installation"
Name: "compact"; Description: "Compact installation - Without documentation"
Name: "bareMinimum"; Description: "The bare minimum - Just the shell and interpreter"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "main"; Description: "ezr² Shell & Interpreter"; Types: full compact bareMinimum custom; Flags: fixed
; Name: "libs"; Description: "ezr² Standard Libraries"; Types: full compact
Name: "docs"; Description: "ezr² Documentation"; Types: full

[Tasks]
Name: "addtopath"; Description: "Add the ezr² Shell to the PATH environment variable"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Dirs]
Name: "{app}\Libraries"

[Files]
Source: "D:\Code\csharp\ezrSquared\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Code\csharp\ezrSquared\Binaries\Shell\Release\net8.0\win-x64\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Code\csharp\ezrSquared\Binaries\Shell\Release\net8.0\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Code\csharp\ezrSquared\docs\_site\docsrc\QuickStartDocumentation.pdf"; DestDir: "{app}\Documentation"; Flags: ignoreversion; Components: docs
Source: "D:\Code\csharp\ezrSquared\docs\_site\api\APIReferenceManual.pdf"; DestDir: "{app}\Documentation"; Flags: ignoreversion; Components: docs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
begin
    if (CurStep = ssPostInstall) and WizardIsTaskSelected('addtopath')
     then EnvAddPath(ExpandConstant('{app}'));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
    if CurUninstallStep = usPostUninstall
    then EnvRemovePath(ExpandConstant('{app}'));
end;

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:WebDocumentation,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:LocalDocumentation,{#MyAppName}}"; Filename: "{app}\Documentation\QuickStartDocumentation.pdf"; Components: docs
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

