encoding: UTF-8
title: ezrSquared
email: info@uralstech.in
description: An easy to learn and practical programming language for beginners and experts alike!
baseurl: ""
url: "https://uralstech.in/"
markdown: kramdown

theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed