title: "ezrSquared"
email: info@uralstech.in
description: An easy to learn and practical programming language for beginners and experts alike!
markdown: kramdown
encoding: UTF-8
author: Uralstech

exclude: ["offline/"]

remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

aux_links:
  "ezrSquared on GitHub":
    - "//github.com/Uralstech/ezrSquared"
aux_links_new_tab: true

search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

callouts:
  warning:
    title: Warning
    color: yellow

nav_external_links:
  - title: ezr² RE Reference Documentation
    url: https://uralstech.github.io/ezrSquaredRefDocs
    opens_in_new_tab: true

footer_content: "ezrSquared is licensed under the <a href=\"https://github.com/Uralstech/ezrSquared/blob/master/LICENSE.txt\">Apache License, Version 2.0</a>."

enable_copy_code_button: true

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Uralstech/ezrSquared"
gh_edit_branch: "ezrSquared-re"
gh_edit_source: docs
gh_edit_view_mode: "tree"