title: ezrSquared
description: >-
  An easy to learn and practical programming language for beginners and experts alike!
email: info@uralstech.in
markdown: kramdown
encoding: UTF-8
baseurl: ""
url: "https://uralstech.in/"
show_downloads: true

theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed