title: ezrSquared
email: info@uralstech.in
description: An easy to learn and practical programming language for beginners and experts alike!
markdown: kramdown
show_downloads: true

remote_theme: just-the-docs/just-the-docs@v0.4.1
plugins:
  - jekyll-feed
  - jekyll-remote-theme