<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputTypes>Library</OutputTypes>
		<RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
		<Platforms>AnyCPU;x64;arm64</Platforms>
		<TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
		<LangVersion>12</LangVersion>

		<ImplicitUsings>Disable</ImplicitUsings>
		<Nullable>Enable</Nullable>
		
		<RootNamespace>EzrSquared</RootNamespace>
		<DebugType>Full</DebugType>

		<PublishSingleFile>True</PublishSingleFile>
		
		<SelfContained>True</SelfContained>
		<IsPublishable>True</IsPublishable>
		
		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup>
		<Product>ezrSquared</Product>
		<PackageId>ezrSquared</PackageId>
		<AssemblyName>ezrSquared-lib</AssemblyName>

		<Title>ezr² Portable Library</Title>
		<Description>The ezr² programming language, as a portable class library! This can be used to integrate ezr² as an embedded scripting language in your apps, websites and more!</Description>
		
		<Version>0.2.0</Version>
		
		<Authors>Udayshankar Ravikumar</Authors>
		<Company>URAV ADVANCED LEARNING SYSTEMS PRIVATE LIMITED</Company>
		<Copyright>© 2022 - 2024 URAV ADVANCED LEARNING SYSTEMS PRIVATE LIMITED</Copyright>

		<NeutralLanguage>en</NeutralLanguage>

		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://uralstech.github.io/ezrSquared/</PackageProjectUrl>
		<PackageTags>programming language;portable;embeddable;compact;interpreted</PackageTags>
		<PackageOutputPath>..\Binaries\ezrSquared\Package</PackageOutputPath>
		
		<RepositoryUrl>https://github.com/uralstech/ezrSquared</RepositoryUrl>

		<PackageIcon>Icon (256x256).png</PackageIcon>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Shell\**" />
	  <EmbeddedResource Remove="Shell\**" />
	  <None Remove="Shell\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\graphics\Icon PNGs\Icon (256x256).png" Pack="True" PackagePath="" />
		<None Include="..\LICENSE.txt" Pack="True" PackagePath="" />
		<None Include="..\README.md" Pack="True" PackagePath="" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
		<PackageReference Include="PolySharp" Version="1.14.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
		<PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
		<DefineConstants>MULTI_TARGETING_SUPPORT_ATTRIBUTES</DefineConstants>
	</PropertyGroup>
</Project>
